</main>
<footer>
<div class="icons text-center">
    <i class="fa-brands fa-instagram" style="color: #cc3333;"></i>
    <i class="fa-brands fa-whatsapp" style="color: green;"></i>
    <i class="fa-brands fa-facebook-messenger" style="color: rgb(172, 223, 254);"></i>
    <i class="fa-brands fa-facebook-f" style="color: blue;"></i>
    <i class="fa-brands fa-tiktok" style="color: black;"></i>
    <i class="fa-brands fa-google" style="color: red;"></i>
</div>


</footer>
<!--footer end-->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></script>
</body>
</html>
